/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Submissions } from "./Submissions";
import { SubmissionsCountArgs } from "./SubmissionsCountArgs";
import { SubmissionsFindManyArgs } from "./SubmissionsFindManyArgs";
import { SubmissionsFindUniqueArgs } from "./SubmissionsFindUniqueArgs";
import { DeleteSubmissionsArgs } from "./DeleteSubmissionsArgs";
import { SubmissionsService } from "../submissions.service";
@graphql.Resolver(() => Submissions)
export class SubmissionsResolverBase {
  constructor(protected readonly service: SubmissionsService) {}

  async _submissionsItemsMeta(
    @graphql.Args() args: SubmissionsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Submissions])
  async submissionsItems(
    @graphql.Args() args: SubmissionsFindManyArgs
  ): Promise<Submissions[]> {
    return this.service.submissionsItems(args);
  }

  @graphql.Query(() => Submissions, { nullable: true })
  async submissions(
    @graphql.Args() args: SubmissionsFindUniqueArgs
  ): Promise<Submissions | null> {
    const result = await this.service.submissions(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Submissions)
  async deleteSubmissions(
    @graphql.Args() args: DeleteSubmissionsArgs
  ): Promise<Submissions | null> {
    try {
      return await this.service.deleteSubmissions(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
